name: sinetestapp #Env name

dependencies:
  - python=3.7
  - pip
  - pip:
      - numpy
      - dash
      - dash-renderer
      - dash-core-components
      - dash-html-components
      - plotly
      - pandas
      - gunicorn # for app deployment